name: file_cache
description: File cached Json,Buffer,FileCacheImage for flutter package project.
version: 0.3.0
homepage: https://github.com/pedia/file_cache

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.16.5
