name: file_cache
description: File cached Json,Buffer,FileCacheImage for flutter package project.
version: 0.3.0
homepage: https://github.com/pedia/file_cache

environment:
  sdk: ">=2.12.0 <4.1.0"

dependencies:
  flutter:
    sdk: flutter

  quiver: ^3.0.0
  path_provider: ^2.0.1
  universal_io: ^2.2.0
  http: ^1.1.0
  logging: ^1.2.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  test: ^1.16.5
  tuple: ^2.0.1
